version: '3'
services:

  fake-logger:
    build: ./src/fake-logger
    container_name: fake-logger
    ports:
      - "8000:8000"
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: fake-logger.{{.ID}}

  telegraf:
    image: telegraf:1.9-alpine
    container_name: telegraf
    volumes:
      - ./src/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - //var/run/docker.sock:/var/run/docker.sock

  influxdb:
    image: influxdb:1.5-alpine
    container_name: influxdb
    environment:
      - INFLUXDB_DB=Metrics
      - INFLUXDB_USER=influx
      - INFLUXDB_USER_PASSWORD=influx
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    links:
      - influxdb

  grafana-init:
    build: ./src/grafana-init
    container_name: grafana-init
    environment:
      - GRAFANA_URL=http://grafana:3000
      - INFLUX_DB=Metrics
      - INFLUX_USER=influx
      - INFLUX_PASSWORD=influx
    links:
      - grafana

  fluentd:
    build: ./src/es-fluentd
    container_name: fluentd
    volumes:
      - ./src/es-fluentd/fluent.conf:/fluentd/etc/fluent.conf
    links:
      - elasticsearch
    ports:
      - "24220:24220"
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.3
    container_name: kibana
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic
    ports:
      - "5601:5601"