version: '3'
services:

  fake-logger:
    build: ./src/fake-logger
    container_name: fake-logger
    ports:
      - "8000:8000"
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: host.docker.internal:24224
        fluentd-async-connect: "true"
        fluentd-buffer-limit: "100mb"
        mode: non-blocking
        tag: fake-logger.{{.ID}}

  telegraf:
    image: telegraf:1.9-alpine
    container_name: telegraf
    volumes:
      - ./src/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - //var/run/docker.sock:/var/run/docker.sock

  influxdb:
    image: influxdb:1.5-alpine
    container_name: influxdb
    environment:
      - INFLUXDB_DB=Metrics
      - INFLUXDB_USER=influx
      - INFLUXDB_USER_PASSWORD=influx
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    links:
      - influxdb

  container-init:
    build: ./src/container-initializer
    container_name: container-init
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - GRAFANA_URL=http://grafana:3000
      - KIBANA_URL=http://kibana:5601
      - INFLUX_DB=Metrics
      - INFLUX_USER=influx
      - INFLUX_PASSWORD=influx
    links:
      - elasticsearch
      - grafana
      - kibana

  fluentd:
    build: ./src/fluentd
    container_name: fluentd
    volumes:
      - ./src/fluentd/fluent.conf:/fluentd/etc/fluent.conf
    links:
      - elasticsearch
    ports:
      - "24220:24220"
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms256m -Xmx256m

  elastic-hq:
    image: elastichq/elasticsearch-hq:release-v3.5.0
    container_name: elastic-hq
    ports:
      - "5000:5000"
    environment:
      HQ_DEFAULT_URL: http://elasticsearch:9200

  curator:
    build: ./src/curator
    container_name: curator
    links:
      - elasticsearch
    environment:
      ES_HOST: elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.3
    container_name: kibana
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic
    ports:
      - "5601:5601"