actions:
  1:
    action: delete_indices
    description: Drop 'fluentd-' indeces older than 2 hours.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: fluentd- # must match the prefix in fluent.conf
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y%m%d-%H'
      unit: hours
      unit_count: 2
      exclude:
  # 2:
  #   action: delete_indices
  #   description: >-
  #      Delete indices older than 1 months (based on index name), for logstash-
  #      prefixed indices. Ignore the error if the filter does not result in an
  #      actionable list of indices (ignore_empty_list) and exit cleanly.
  #   options:
  #     ignore_empty_list: True
  #     timeout_override:
  #     continue_if_exception: True
  #     disable_action: False
  #   filters:
  #   - filtertype: pattern
  #     kind: prefix
  #     value: logstash-
  #     exclude:
  #   - filtertype: age
  #     source: name
  #     direction: older
  #     timestring: '%Y%m%d'
  #     unit: months
  #     unit_count: 3
  #     exclude: