{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": "SELECT distinct(container_name) FROM (SELECT pid, container_name FROM \"docker.docker_container_status\")"
   }
  ]
 },
 "panels": [
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Docker Containers - CPU Load - $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker.docker_container_cpu",
     "query": "SELECT sum(\"usage_percent\") FROM \"docker.docker_container_cpu\" WHERE $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "content": "# Overview\n\nSee also:\n- [Kibana](http://localhost:5601)\n- [ElasticHQ](http://localhost:5000/)"
  },
  {
   "title": "Docker Containers - Memory Usage - $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker.docker_container_mem",
     "query": "SELECT mean(\"usage_percent\") FROM \"docker.docker_container_cpu\" WHERE $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$/" }
     ]
    }
   ]
  },
  {
   "title": "Elastic Search - Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "elasticsearch.elasticsearch_indices",
     "query": "SELECT max(\"translog_size_in_bytes\") AS \"Translog\", max(\"store_size_in_bytes\") AS \"Store\" FROM \"elasticsearch.elasticsearch_indices\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "translog_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Translog" ], "type": "alias" }
      ],
      [
       { "params": [ "store_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Store" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "fluentd - Buffer Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes", "label": "Buffer Queue Size" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fluentd.fluentd",
     "select": [
      [
       { "params": [ "buffer_total_queued_size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Buffer Queue Size" ], "type": "alias" }
      ],
      [
       { "params": [ "buffer_queue_length" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Buffer Queue Length" ], "type": "alias" }
      ],
      [
       { "params": [ "retry_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Retry Count" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Fake Logger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Log Messages Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fake-logger.app_logged_msg_total",
     "query": "SELECT non_negative_difference(mean(\"counter\")) FROM \"autogen\".\"fake-logger.app_logged_msg_total\" WHERE $timeFilter GROUP BY time($__interval), \"level\" fill(null)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fake-logger.app_logged_msg_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Messages (Σ)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 24 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fake-logger.app_logged_msg_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "Error" }
     ]
    }
   ]
  },
  {
   "title": "Info Messages (Σ)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 26 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fake-logger.app_logged_msg_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "Info" }
     ]
    }
   ]
  },
  {
   "title": "Debug Messages (Σ)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 28 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fake-logger.app_logged_msg_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "Debug" }
     ]
    }
   ]
  },
  {
   "title": "Logging Pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Logging Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fake-logger.app_current_pressure_percent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}